# Generated by Django 4.0.1 on 2022-01-18 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_tags',
            field=models.ManyToManyField(to='projects.ProjectTag'),
        ),
    ]
