# Generated by Django 4.0.1 on 2022-01-20 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_images_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
